package com.example.usedaoforgen.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CHANNEL.
 */
public class Channel {

    private Long id;
    /** Not-null value. */
    private String ID;
    /** Not-null value. */
    private String name;
    private String url;
    private String source;

    public Channel() {
    }

    public Channel(Long id) {
        this.id = id;
    }

    public Channel(Long id, String ID, String name, String url, String source) {
        this.id = id;
        this.ID = ID;
        this.name = name;
        this.url = url;
        this.source = source;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getID() {
        return ID;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setID(String ID) {
        this.ID = ID;
    }

    /** Not-null value. */
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String name) {
        this.name = name;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getSource() {
        return source;
    }

    public void setSource(String source) {
        this.source = source;
    }

}
