package com.example.usedaoforgen.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table POSITION.
 */
public class POSITION {

    private Long id;
    /** Not-null value. */
    private String TEL;
    private Double X;
    private Double Y;
    private Float SPEED;
    private String ACCURACY;
    private String STRTIME;
    private java.util.Date TIME;
    private String DEVICEID;

    public POSITION() {
    }

    public POSITION(Long id) {
        this.id = id;
    }

    public POSITION(Long id, String TEL, Double X, Double Y, Float SPEED, String ACCURACY, String STRTIME, java.util.Date TIME, String DEVICEID) {
        this.id = id;
        this.TEL = TEL;
        this.X = X;
        this.Y = Y;
        this.SPEED = SPEED;
        this.ACCURACY = ACCURACY;
        this.STRTIME = STRTIME;
        this.TIME = TIME;
        this.DEVICEID = DEVICEID;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getTEL() {
        return TEL;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTEL(String TEL) {
        this.TEL = TEL;
    }

    public Double getX() {
        return X;
    }

    public void setX(Double X) {
        this.X = X;
    }

    public Double getY() {
        return Y;
    }

    public void setY(Double Y) {
        this.Y = Y;
    }

    public Float getSPEED() {
        return SPEED;
    }

    public void setSPEED(Float SPEED) {
        this.SPEED = SPEED;
    }

    public String getACCURACY() {
        return ACCURACY;
    }

    public void setACCURACY(String ACCURACY) {
        this.ACCURACY = ACCURACY;
    }

    public String getSTRTIME() {
        return STRTIME;
    }

    public void setSTRTIME(String STRTIME) {
        this.STRTIME = STRTIME;
    }

    public java.util.Date getTIME() {
        return TIME;
    }

    public void setTIME(java.util.Date TIME) {
        this.TIME = TIME;
    }

    public String getDEVICEID() {
        return DEVICEID;
    }

    public void setDEVICEID(String DEVICEID) {
        this.DEVICEID = DEVICEID;
    }

}
